- name: Play Variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: Play Variables from files
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from file
      ansible.builtin.debug:
        msg: URL = {{ URL }}



- name: task level variables
  hosts: localhost
  tasks:
    - name: print play variable
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}


